/home/renchengwei/blender-4.4.3-linux-x64/blender -b -P depth_mask_fixed_obj_long.py -- \
    --object_path glb_objs \
    --plane_path glb_planes \
    --output_dir ./views_depth_mask_fixed_obj_long \
    --engine CYCLES \
    --mode full \
    --num_images 240 \
    --camera_type fixed \
    --camera_dist_min 16 \
    --camera_dist_max 32 \
    --elevation_min 10 \
    --elevation_max 45 \
    --enable_other_objects "${ENABLE_OTHER_OBJECTS:-0}" \
    --res_w 640 \
    --res_h 480 \
    --camera_path_segments_min 10 \
    --camera_path_segments_max 24 \
    --camera_path_segment_len_min 12 \
    --camera_path_segment_len_max 18 \
    --camera_path_attempts 140 \
    --camera_az_step_deg_min 10 \
    --camera_az_step_deg_max 36 \
    --camera_el_step_deg_max 8 \
    --camera_dist_step_ratio_min 0.02 \
    --camera_dist_step_ratio_max 0.10 \
    --camera_min_xyz_step_ratio 0.10 \
    --hdrs_dir /home/renchengwei/bpy_render/hdri_bgs \
    --silent_mode
